name: Bug Report
description: Report a bug in rfmt
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: input
    id: rfmt-version
    attributes:
      label: rfmt version
      description: Run `rfmt --version` or check your Gemfile.lock
      placeholder: "1.2.7"
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: Ruby version
      description: Run `ruby -v`
      placeholder: "ruby 3.3.0 (2023-12-25 revision 5124f9ac75)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x86_64)
        - Linux (ARM64)
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Code
      description: |
        Minimal Ruby code that reproduces the issue.
        This will be automatically formatted as Ruby code.
      render: ruby
      placeholder: |
        # Minimal code to reproduce
        class Example
          def foo
            # ...
          end
        end
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: |
        Full error message or unexpected output.
        This will be automatically formatted as a code block.
      render: shell
      placeholder: |
        $ rfmt example.rb
        Error: ...

  - type: textarea
    id: config
    attributes:
      label: Configuration (if applicable)
      description: |
        Contents of your rfmt.yml if you're using custom configuration.
        This will be automatically formatted as YAML.
      render: yaml
      placeholder: |
        formatting:
          line_length: 100
          indent_width: 2

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, related issues, etc.)
